  # Usman Sensors-0x
  sensor:  
    - name: "UA-Sensor Temperature-0X"
      state_topic: "stat/ua-sensor0x/temperature"
      icon: mdi:thermometer
      # friendly_name: "UA-Sensor Temperature"
      unit_of_measurement: "*C"

    - name: "UA-Sensor Humidity-0X"
      icon: mdi:thermometer-lines
      state_topic: "stat/ua-sensor0x/humidity"
      # friendly_name: "UA-Sensor Humidity"
      unit_of_measurement: "%"

    - name: "UA-Sensor Pressure-0X"
      icon: mdi:water-percent
      state_topic: "stat/ua-sensor0x/pressure"
      # friendly_name: "UA-Sensor pressure?"
      unit_of_measurement: "hPa"

    - name: "UA-Sensor IAQ (gas)-0X"
      icon: mdi:image-filter-drama
      state_topic: "stat/ua-sensor0x/gasResistance"
      # friendly_name: "UA-Sensor IAQ"
      unit_of_measurement: "k0hm"
      
    - name: "UA-Sensor Name-0X"
      icon: mdi:image-filter-drama
      state_topic: "stat/ua-sensor0x/matrikelnummer"
      # friendly_name: "UA-Sensor IAQ"
      unit_of_measurement: ":Matrikelnummer"


  
# add "mqtt: !include mqtt_config.yaml" to your main 'config.yaml' in Home Assistant
# then add this file to the same directory as the 'config.yaml'
# then fully restart your HA.
# your HA only needs to be rebooted once after that you can just reload the yaml configs in "developer settings"
